### ISSUE TITLE
Suggested Enhancment

### ISSUE THREAD

**Issue by ghost** [ARMmbed/mbed-stress-test#1]
Would be good to have two additional tests related to network:
1. Tx large data file test, make sure that non-blocking is working correctly
2. Mixed Rx/Tx, request data (RX) followed immediately by TX and TX immediately followed by RX to make sure that work together an there are no unexpected interactions.

**Comment by marcuschangarm** [comment]
Thank you for the feedback!

Do you have a suggestion for where to send large amounts of data? I would like to avoid having to maintain a server to test against.

**Comment by ghost** [comment]
As a suggestion, you could do something like download one of your large files, have the test SW  calculate the CRC across the document received, then send that document + CRC back to a URL that can receive and calculate the CRC to verify that it was received correctly and sent correctly.  It would be easier if you had a dedicated server but I understand the desire to avoid that.
