### ISSUE TITLE
multiple-http test

### ISSUE THREAD

**Issue by ghost** [ARMmbed/mbed-stress-test#5]
Hi, I've been running the stress-network-multiple-http tests and noticed a event I was curious about.  When running with multiple threads the following is occurring:
[1523321784.99][CONN][RXD] result (3): 1024
[1523321785.00][CONN][RXD] 3: received_bytes: 34948
[1523321785.09][CONN][RXD] result (3): 1024
[1523321785.09][CONN][RXD] 3: received_bytes: 35972
[1523321785.20][CONN][RXD] result (3): 1024
[1523321785.20][CONN][RXD] 3: received_bytes: 36996
[1523321785.30][CONN][RXD] result (3): 1024
[1523321785.30][CONN][RXD] 3: received_bytes: 38020
[1523321785.40][CONN][RXD] result (3): 1024
[1523321785.40][CONN][RXD] 3: received_bytes: 39044
[1523321785.46][CONN][RXD] result (3): 564
[1523321785.46][CONN][RXD] 3: received_bytes: 39608
**[1523321785.47][CONN][RXD] result (3): -3001
[1523321785.48][CONN][RXD] result (3): -3001**
[1523321802.57][CONN][RXD]
[1523321802.57][CONN][RXD] EXIT rx_event(), socket id 3, rx data TIME-OUT!
[1523321802.57][CONN][RXD]
[1523321802.57][CONN][RXD] Call socket 3 RX call-back
[1523321802.58][CONN][RXD] result (3): 0

So my socket is timing out, I perform the callback and report 0 bytes were received, but the test never calls back again or terminates the test. Do you have any thoughts on what would cause this to occur?
I expected that the test would keep calling until it either gave up and failed, or would simply fail at that point and terminate the test.  I looks like it is simply hanging at the:

        while(!event_fired[thread_id]) {
            Thread::yield();
        }

I modified the test as follows to simply keep it from hanging forever...
``` 
Timer t;
t.start();
        while(!event_fired[thread_id] && t.read_ms() < 30000 ) {
            Thread::yield();
        }
t.stop();
```
probably not the right fix, but I wanted to avoid an infinite loop. I wonder if there is a race condition happening with the event_fired variable.  BTW, I have background reads happening in an EventQueue  routine so it is possible that the variable is being accessed from two different threads (the main thread and an event thread).  The WOULD_BLOCK returns are occurring when a read has been requested and is in-flight but not yet completed. Any ideas or thoughts?

**Comment by marcuschangarm** [comment]
Hi! If the socket is timing out I would expect one of the errors to be returned:

https://github.com/ARMmbed/mbed-os/blob/master/features/netsocket/nsapi_types.h#L37-L57

I think the value 0 is only allowed if everything went according to plan.

**Comment by ghost** [comment]
In that case, which error would be appropriate, everything is working correctly, there simply wasn't any data to return.  Would you just keep returning WOULD_BLOCK?  BTW, I wrapped the 'event-fired' in mutexes (when it is updated in the thread and callback) and the test started working as expected.

**Comment by marcuschangarm** [comment]
Ah, I might have misunderstood what you are saying then. Could you please elaborate:

1. Exactly what is timing out?
1. The file should be 167546 bytes. More data should be on its way?
1. The `recv` command is called after the `event-fired` flag is set. I would expect the `recv` call to re-arm the socket so that the event would fire again when there is more data to be read by `recv`.

Thanks!

**Comment by ghost** [comment]
The problem was that the socket was timing out, the call-back was called to set event-fired, but somehow the even-fired event was cleared before it had a chance to be acted on. So the test was sitting in the loop waiting for event-fired to be set (but it had already been set, then subsequently cleared by someone).

I put a Mutex around the event-fired setting and clearing which appeared to fix the problem.
